const ACTIVE_ID_REQUEST = 'ACTIVE_ID_REQUEST';
const ACTIVE_ID_SUCCESS = 'ACTIVE_ID_SUCCESS';
const ACTIVE_ID_FAILURE = 'ACTIVE_ID_FAILURE';

export {
  ACTIVE_ID_REQUEST,
  ACTIVE_ID_SUCCESS,
  ACTIVE_ID_FAILURE,
}
