const ADD_NOTIFICATION_REQUEST = 'ADD_NOTIFICATION_REQUEST';
const ADD_NOTIFICATION_SUCCESS = 'ADD_NOTIFICATION_SUCCESS';
const ADD_NOTIFICATION_FAILURE = 'ADD_NOTIFICATION_FAILURE';
export {
  ADD_NOTIFICATION_REQUEST,
  ADD_NOTIFICATION_SUCCESS,
  ADD_NOTIFICATION_FAILURE,
}
