const CHANGE_MEDIA_SERVER_REQUEST = 'CHANGE_MEDIA_SERVER_REQUEST';
const CHANGE_MEDIA_SERVER_SUCCESS = 'CHANGE_MEDIA_SERVER_SUCCESS';
const CHANGE_MEDIA_SERVER_FAILURE = 'CHANGE_MEDIA_SERVER_FAILURE';
export {
  CHANGE_MEDIA_SERVER_REQUEST,
  CHANGE_MEDIA_SERVER_SUCCESS,
  CHANGE_MEDIA_SERVER_FAILURE,
}