const CREATE_NOTIFICATION_REQUEST = 'CREATE_NOTIFICATION_REQUEST';
const CREATE_NOTIFICATION_SUCCESS = 'CREATE_NOTIFICATION_SUCCESS';
const CREATE_NOTIFICATION_FAILURE = 'CREATE_NOTIFICATION_FAILURE';
export {
  CREATE_NOTIFICATION_REQUEST,
  CREATE_NOTIFICATION_SUCCESS,
  CREATE_NOTIFICATION_FAILURE,
}
