const SERVER_LIST_REQUEST = 'SERVER_LIST_REQUEST';
const SERVER_LIST_SUCCESS = 'SERVER_LIST_SUCCESS';
const SERVER_LIST_FAILURE = 'SERVER_LIST_FAILURE';
export {
  SERVER_LIST_REQUEST,
  SERVER_LIST_SUCCESS,
  SERVER_LIST_FAILURE,
}
